version: '3.3'

services:
  web:
    image: registry.gitlab.com/mangoads/mgs/web-client:latest
    networks:
      - net
      - traefik
    deploy:
      # placement:
      #   constraints:
      #     - node.hostname == worker-hoasen
      labels:
        traefik.http.routers.web-client.service: web-client
        traefik.http.routers.web-client_tls.rule: Host(`web-client.internal.mangoads.com.vn`)
        traefik.http.services.web-client.loadbalancer.server.port: '3000'
        traefik.http.routers.web-client_tls.tls: 'true'
        traefik.http.routers.web-client.rule: Host(`web-client.internal.mangoads.com.vn`)
        traefik.http.routers.web-client_tls.service: web-client
        traefik.docker.network: traefik
        traefik.enable: 'true'
        traefik.http.routers.web-client_tls.tls.certresolver: myresolver
networks:
  net:
    driver: overlay
  traefik:
    external: true
